export const PASSWORD_CHANGE = '/src/containers/PasswordChangePage/PASSWORD_CHANGE';
export const PASSWORD_CHANGE_FULFILLED = `${PASSWORD_CHANGE}_FULFILLED`;
export const PASSWORD_CHANGE_REJECTED = `${PASSWORD_CHANGE}_REJECTED`;
export const PASSWORD_CHANGE_PENDING = `${PASSWORD_CHANGE}_PENDING`;
