export const UPLOAD_VACANCY = 'src/containers/NewVacancy/UPLOAD_VACANCY';
export const UPLOAD_VACANCY_FULFILLED = `${UPLOAD_VACANCY}_FULFILLED`;
export const UPLOAD_VACANCY_REJECTED = `${UPLOAD_VACANCY}_REJECTED`;
export const UPLOAD_VACANCY_PENDING = `${UPLOAD_VACANCY}_PENDING`;

export const LOAD_CATEGORIES = 'src/containers/NewVacancy/LOAD_CATEGORIES';
export const LOAD_CATEGORIES_FULFILLED = `${LOAD_CATEGORIES}_FULFILLED`;
export const LOAD_CATEGORIES_REJECTED = `${LOAD_CATEGORIES}_REJECTED`;
export const LOAD_CATEGORIES_PENDING = `${LOAD_CATEGORIES}_PENDING`;

export const LOAD_KEYWORDS = 'src/containers/NewVacancy/LOAD_KEYWORDS';
export const LOAD_KEYWORDS_FULFILLED = `${LOAD_KEYWORDS}_FULFILLED`;
export const LOAD_KEYWORDS_REJECTED = `${LOAD_KEYWORDS}_REJECTED`;
export const LOAD_KEYWORDS_PENDING = `${LOAD_KEYWORDS}_PENDING`;

export const LOAD_CITIES = 'src/containers/NewVacancy/LOAD_CITIES_VALUES';
export const LOAD_CITIES_FULFILLED = `${LOAD_CITIES}_FULFILLED`;
export const LOAD_CITIES_REJECTED = `${LOAD_CITIES}_REJECTED`;
export const LOAD_CITIES_PENDING = `${LOAD_CITIES}_PENDING`;

export const LOAD_COUNTRIES = 'src/containers/NewVacancy/LOAD_COUNTRIES_VALUES';
export const LOAD_COUNTRIES_FULFILLED = `${LOAD_COUNTRIES}_FULFILLED`;
export const LOAD_COUNTRIES_REJECTED = `${LOAD_COUNTRIES}_REJECTED`;
export const LOAD_COUNTRIES_PENDING = `${LOAD_COUNTRIES}_PENDING`;
