export const LOAD_VACANCY = 'src/containers/VacancyDetail/LOAD_VACANCY';
export const LOAD_VACANCY_FULFILLED = `${LOAD_VACANCY}_FULFILLED`;
export const LOAD_VACANCY_REJECTED = `${LOAD_VACANCY}_REJECTED`;
export const LOAD_VACANCY_PENDING = `${LOAD_VACANCY}_PENDING`;

