export const SUBMIT_CREDENTIALS = '/src/containers/SignupPageContainer/SUBMIT_CREDENTIALS';
export const SUBMIT_CREDENTIALS_FULFILLED = `${SUBMIT_CREDENTIALS}_FULFILLED`;
export const SUBMIT_CREDENTIALS_REJECTED = `${SUBMIT_CREDENTIALS}_REJECTED`;
export const SUBMIT_CREDENTIALS_PENDING  = `${SUBMIT_CREDENTIALS}_PENDING`;
