export const LOAD_VACANCIES = 'src/containers/Vacancies/LOAD_VACANCIES';
export const LOAD_VACANCIES_FULFILLED = `${LOAD_VACANCIES}_FULFILLED`;
export const LOAD_VACANCIES_REJECTED = `${LOAD_VACANCIES}_REJECTED`;
export const LOAD_VACANCIES_PENDING = `${LOAD_VACANCIES}_PENDING`;

export const UPDATE_SEARCH_STRING = 'src/containers/Vacancies/CHANGE_SEARCH_STRING';

